name = "erdos_945"
version = "0.1.0"
defaultTargets = ["Erdos945"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "0df444a360eaa60ab8c11dca51a86af692955474"

[[lean_lib]]
name = "Erdos945"
